### ISSUE TITLE
project dead?

### ISSUE THREAD

**Issue by johanneswilm** [NYTimes/ice#114]
Hey,
I noticed that nothing has been committed for half a year. Changes to Chrome and other browsers do that this plugin is getting less and less usable unless it is maintained. So quetion: is this project dead or is someone maintaining it?

**Comment by pcraston** [comment]
Hi all. I put in some work recently to make ICE work with TinyMCE4. Submitted a pull request https://github.com/NYTimes/ice/pull/116 but haven't had any response. So should someone need TinyMCE4 support, please check out our fork at https://github.com/ctxis/ice

**Comment by catsgotmytongue** [comment]
Yeah it seemed dead when I did some work on it a year ago.

**Comment by delambo** [comment]
I added a call for help issue. It looks like @itmilos is trying to revive things...
